const Categories$FbtEnum = {
  'schema.forSale': 'For Sale',
  'schema.forRent': 'For Rent',
  'schema.services': 'Services',
  'schema.announcements': 'Announcements',
  'schema.antiques': 'Antiques',
  'schema.appliances': 'Appliances',
  'schema.artsCrafts': 'Arts and Crafts',
  'schema.atvsUtvsSnowmobiles': 'Atvs, Utvs, Snowmobiles',
  'schema.autoParts': 'Auto Parts',
  'schema.autoWheelsTires': 'Auto Wheels and Tires',
  'schema.babyKidStuff': 'Baby and Kid Stuff',
  'schema.bicycleParts': 'Bicycle Parts',
  'schema.bicycles': 'Bicycles',
  'schema.boatPartsAccessories': 'Boat Parts and Accessories',
  'schema.boats': 'Boats',
  'schema.booksMagazines': 'Books and Magazines',
  'schema.businesses': 'Businesses',
  'schema.carsTrucks': 'Cars and Trucks',
  'schema.cdsDvdsVhs': 'CDs, DVDs, VHS',
  'schema.cellPhones': 'Cell Phones',
  'schema.clothingAccessories': 'Clothing and Accessories',
  'schema.collectibles': 'Collectibles',
  'schema.computerParts': 'Computer Parts',
  'schema.computers': 'Computers',
  'schema.electronics': 'Electronics',
  'schema.farmGarden': 'Farm and Garden',
  'schema.furniture': 'Furniture',
  'schema.healthBeauty': 'Health and Beauty',
  'schema.heavyEquipment': 'Heavy Equipment',
  'schema.householdItems': 'Household Items',
  'schema.jewelry': 'Jewelry',
  'schema.materials': 'Materials',
  'schema.motorcyclePartsAccessories': 'Motorcycle Parts and Accessories',
  'schema.motorcyclesScooters': 'Motorcycles and Scooters',
  'schema.musicalInstruments': 'Musical Instruments',
  'schema.other': 'Other',
  'schema.photoVideo': 'Photo and Video',
  'schema.realEstate': 'Real Estate',
  'schema.recreationalVehicles': 'Recreational Vehicles',
  'schema.sportingGoods': 'Sporting Goods',
  'schema.tickets': 'Tickets',
  'schema.tools': 'Tools',
  'schema.toysGames': 'Toys and Games',
  'schema.trailers': 'Trailers',
  'schema.videoGaming': 'Video Gaming',
  'schema.housing': 'Housing',
  'schema.parking': 'Parking',
  'schema.storage': 'Storage',
  'schema.counseling': 'Counseling',
  'schema.design': 'Design',
  'schema.dogWalking': 'Dog Walking',
  'schema.musicLessons': 'Music Lessons',
  'schema.photography': 'Photography',
  'schema.salon': 'Salon',
  'schema.spa': 'Spa',
  'schema.transportation': 'Transportation',
  'schema.activities': 'Activities',
  'schema.artists': 'Artists',
  'schema.barter': 'Barter',
  'schema.childcare': 'Childcare',
  'schema.classes': 'Classes',
  'schema.freeStuff': 'Free Stuff',
  'schema.garageMovingSales': 'Garage and Moving Sales',
  'schema.general': 'General',
  'schema.groups': 'Groups',
  'schema.localNews': 'Local News',
  'schema.lostFound': 'Lost and Found',
  'schema.marketing': 'Marketing',
  'schema.musicians': 'Musicians',
  'schema.personals': 'Personals',
  'schema.pets': 'Pets',
  'schema.politics': 'Politics',
  'schema.resumes': 'Resumes',
  'schema.volunteers': 'Volunteers'
}

module.exports = Categories$FbtEnum
