"""empty message

Revision ID: 8731cde0bd1e
Revises: 65daf2256cbe
Create Date: 2018-10-05 17:30:07.689881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8731cde0bd1e'
down_revision = '65daf2256cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'attestation',
        sa.Column('remote_ip_address', postgresql.INET(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attestation', 'remote_ip_address')
    # ### end Alembic commands ###
