FROM node:10

WORKDIR /app

ENV NODE_ENV=development

# Copy utility scripts
COPY ./development/scripts/* /usr/local/bin/

COPY ./scripts/ ./scripts/

# Copy all package files for dependency installs, this is done here to allow
# Docker to cache the npm install steps if none of the dependencies have changed
COPY ./lerna.json ./
COPY ./package.json ./
COPY ./origin-contracts/package.json ./origin-contracts/
COPY ./origin-discovery/package.json ./origin-discovery/
COPY ./origin-growth/package.json ./origin-growth/
COPY ./origin-ipfs-proxy/package.json ./origin-ipfs-proxy/
COPY ./origin-js/package.json ./origin-js/
COPY ./origin-messaging/package.json ./origin-messaging/
COPY ./origin-notifications/package.json ./origin-notifications/
COPY ./origin-tests/package.json ./origin-tests/
COPY ./experimental/origin-graphql/package.json ./experimental/origin-graphql/
COPY ./experimental/origin-ipfs/package.json ./experimental/origin-ipfs/
COPY ./experimental/origin-validator/package.json ./experimental/origin-validator/
COPY ./experimental/origin-messaging-client/package.json ./experimental/origin-messaging-client/
COPY ./experimental/origin-eventsource/package.json ./experimental/origin-eventsource/
COPY ./experimental/origin-services/package.json ./experimental/origin-services/
COPY ./experimental/origin-admin/package.json ./experimental/origin-admin/
COPY ./experimental/origin-dapp2/package.json ./experimental/origin-dapp2/

# Running of postinstall script requires --unsafe-perm
RUN npm install --unsafe-perm --no-scripts

# Build origin-js for event-listener
RUN npm run build --prefix origin-js
