FROM node:10

WORKDIR /app

# Copy utility scripts
COPY ./development/scripts/* /usr/local/bin/

COPY ./scripts/ ./scripts/

# Copy all package files for dependency installs, this is done here to allow
# Docker to cache the npm install steps if none of the dependencies have changed
COPY ./lerna.json ./
COPY ./package.json ./
COPY ./origin-discovery/package.json ./origin-discovery/
COPY ./origin-ipfs-proxy/package.json ./origin-ipfs-proxy/
COPY ./origin-js/package.json ./origin-js/
COPY ./origin-messaging/package.json ./origin-messaging/
COPY ./origin-notifications/package.json ./origin-notifications/
COPY ./origin-tests/package.json ./origin-tests/
COPY ./origin-growth/package.json ./origin-growth/
COPY ./origin-identity/package.json ./origin-identity/
COPY ./origin-token/package.json ./origin-token/
COPY ./origin-bridge/package.json ./origin-bridge/
COPY ./experimental/origin-dapp2/package.json ./experimental/origin-dapp2/
COPY ./experimental/origin-graphql/package.json ./experimental/origin-graphql/
COPY ./experimental/origin-ipfs/package.json ./experimental/origin-ipfs/
COPY ./experimental/origin-validator/package.json ./experimental/origin-validator/
COPY ./experimental/origin-messaging-client/package.json ./experimental/origin-messaging-client/
COPY ./experimental/origin-linker-client/package.json ./experimental/origin-linker-client/
COPY ./experimental/origin-eventsource/package.json ./experimental/origin-eventsource/
COPY ./experimental/origin-services/package.json ./experimental/origin-services/

# Complete contracts source needs to be available so that `truffle compile contracts`
# which is calleed by the prepare script can succeed
COPY ./origin-contracts ./origin-contracts
COPY ./origin-js ./origin-js

# Running of postinstall script requires --unsafe-perm
RUN npm install --unsafe-perm

# Build origin-js for event-listener
RUN npm run build --prefix origin-js
