# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OriginCatcher' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OriginCatcher

  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'


  target 'OriginCatcherTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'OriginCatcher-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OriginCatcher-tvOS

  target 'OriginCatcher-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
