export const GiftCardRetailers = {
  '─────────────': '',
  Amazon: 'QmcBdqfucZfjw1fXsdvoH9Mt8HhaZCxQRF63N1utctJMV8',
  Walmart: 'QmYMChXc6R1kT3jrjfGXcDMe5AgS8VxuhUFhEVZES2Hrob',
  iTunes: 'QmaUdJ6ZoRqkSqdt685UeXYoawAKxMqQV7Ud9vmX5iDRSS',
  Starbucks: 'QmS3cxoJiYVxiaTdLefR39pY85mgQRn36XYeyehFJcdbyY',
  Target: 'Qmah8TdFHNVNjHFyFzN1eT37uVoa93ZGsP3jLdHUfgWDwm',
  '──────────────': '',
  '1-800-Baskets': 'Qmb7CSZbheb4S1H77MjJ7eogT56LMM5yyjfjrrbMgWn5tH',
  '1-800-Flowers.com': 'QmPVH3zDgnC6qBP4AWdhmUrBMmaHn2X7XcfELVBS4Phcop',
  '16 Handles': 'QmaRwM8CA6BBczqkMouBZBBDjCW36QhGyQPnanGt9UptST',
  'A Pea in the Pod': 'Qmb1hUESCzWisr2SgdHzEsBGrYwXHZezncXzcd24Ntu2Fv',
  'Abercrombie & Fitch': 'QmYS26LSLh2HuFS1tvxcUZ55TTBmZNTChZLpj1gtg2GZx9',
  'Abercrombie Kids': 'QmQHUFWj5DGrQ2NFNhGDJDXNTPjGhzpcvsvv4idFHA71fJ',
  'Academy Sports & Outdoors': 'QmNkMcsNXUddAqvk7AYJvSaAhsVAdUa4KKunUgPErZTe7J',
  Active: 'QmUbURsDwYTxqcGoiujCXCrP7GzGfqYhqbyphyvfCnoymF',
  'Advance Auto Parts': 'QmPPmw2YvQs4tewZBrhk7t6c9MrtDFxTGrahomqp54PeB6',
  Aerie: 'QmPkdzRxW4FU7JkWsvcM4GwEVn5wsuiHPXDeEJPhABEQzp',
  Aeropostale: 'QmYgHGaGHnNHRhjSpQj75GSyGLSk4na3xcBwav8CpYQ85N',
  Aerosoles: 'QmPVqGPQ5NeGqSKWcCy18JR7GUTLUmjVRsYhvvg2gKqb5K',
  AirBnB: 'QmaBRXiduZ91B2DHDHXFH3x81i9CpFDC5PtexPNJnAymsa',
  'Alamo Drafthouse Cinema': 'Qmc2CgjyU5DpeZx1mKRC7PTbTakV1pMMPZ8E35Z8i1REGq',
  ALDO: 'QmY4VrM4VJefmx8mcjkuQoHsSF8qJL4KqULUNoGdCfUMdT',
  'Alex and Ani': 'QmSPFyfKEphcmUWMkS26wCMUJb4QVgD4QXhvw41NcZKoCY',
  'Alice and Olivia': 'QmaAgUSUETiEQ5hDPcScgg55XmWX5AM7ZAEGV5rEwFGsKb',
  'All Saints': 'QmX3AbkqxmsWhMzYiRRE4vWU7XQnDp5XMfXkug6EXwz95L',
  'Allen Edmonds': 'QmTxQaxAnvRMU9ExpzfPKim9sD1fRenQeMz2wooHND92nF',
  "Altar'd State": 'QmReV6aRSN3TmhieXA4JkfPJFs1WJHzyLaCdaKVzK4TT3K',
  'AMC Theatres': 'QmW8PpCjxvZEenwc1euPT6WJSF1J8EhdgjQq43mvytQv2m',
  'American Airlines': 'QmTmF7KZYRdNGEd5Qtj7y7B38P99tyKZVVZYf1f6BvnoHk',
  'American Eagle Outfitters': 'QmR2VbzQSueCq1Qdym6xsz52CQoAdF74xLVqbJX43uWmUA',
  'Apple iTunes': 'QmciaMX1yK6rW4vqrw1T3wmQr9GyYAbXprDpgoRY2ZZevG',
  'Apple Store (not iTunes)': 'QmVyoy6csnwE4tTfspGYM8doK6YCGArNdrmkfHGrK8fXRH',
  "Applebee's": 'QmRcNwZ2x9BcSjss3ABHUHP7AdZQzRC57AgsA91okyuTkE',
  'Aquarium Restaurants': 'QmZFWoQbzQf5Lch5FEAJHHJkyWktNWuoGJhaWraPxb461G',
  Athleta: 'QmSVVSkyPaYR71uzPgA4pN2M1cg38WG3LmwCKA2Gv9uZGi',
  "Atria's Restaurant": 'QmWqhjhyLWWsemPXpXxkA2q9J19AWWvMEpyfGhZgPUzSZS',
  AutoZone: 'QmPCWVWvi4Gbm5KC65ZUYzyf6hzFBJ2UNFRDqEaiZE6CAW',
  'Baby Gap': 'QmS6hxCDixLeoVNYC9Jg2rL9zx3WfbavrQrsyMDmz5asqu',
  'Banana Republic': 'QmPA9WfmwdfF8n8tqN6ocNNg8yKE8Z9EDrnVV3WC3i4C8j',
  'Bare Minerals': 'QmYqg6ZYiDzjHzLNnGKcJe4NHW8AydFgHoWgSVjezimWkm',
  'Barnes & Noble': 'QmcCaZ9KQbjFAQVDG1ijdgi5gp7SYgitRuTJ731DffoKtp',
  "Barney's New York": 'QmbtvtH1wCaK7qaKgk3xE5RjvAubi6i72yq3pQXCn7Ao7Z',
  'Bass Pro Shops': 'QmXEiPBgSGYiiNBWwnqaugiXvDjKpNvHqgdmjDhFC2EZ2F',
  'Bath & Body Works': 'QmR3ZfSs31qnUspuVMK8gcyZpTwnHQFJ6fAbC6wvx9Ewis',
  'Bealls Outlet (Florida)': 'QmWAe4p11fWCBGRjYvbcoxKvS5Lo4Q9kxrUUexdq3h39zw',
  "Beau Jo's": 'QmQRNuUpZoPo2pjcjXpEPKQHhCVaUF4sxw4C8cED3MGYa8',
  Bebe: 'QmRoLsfzKmpcM1mohZFG4wc9XTUZCnJBBuBh2rbV4FrFgw',
  'Bed Bath and Beyond': 'QmcifcwcB5Z869xxMcPeRqfzWAwAXbP4sxNMqfyQvtLKhM',
  'BedandBreakfast.com': 'QmW9kbXXPhRbDA2TARwu1JtgC1MmaKcBBNmuBArQ5pR9SZ',
  Belk: 'QmWeigSz3Gxjo9BcFdNTjTW9g8uThXKfhFUA9R58bKL2eK',
  'Best Buy': 'QmeHezguo1sEEaEPizQ4SEcztFwDeG7dQJBt7ZdoGDTkcm',
  BevMo: 'QmRWzUtZo2uDyYS7kCvvbiqbUqAM9UwwHGE7pE6NvTHfow',
  'Big Lots': 'Qmc4sXYWgdghut1L7G9U6dKkXKKCHwUX6eySBhY7vUwKrk',
  "BJ's Restaurant and Brewhouse":
    'QmP9VMUDsiTDFxAkphPTeqc41ZA5iVScqj1DZFBooE2Dop',
  Blair: 'QmQQGAJgXbGPrNonuG4khrTBARUWfqY4M8W91YSP35ec22',
  'Blick Art Materials': 'QmT316ZnAVcALeydQwHgLdKWrtcmMCxYok2kpSeB6jaMtp',
  'Bliss Spa': 'QmSwk7N9mBXYB67ESheg3Ho65682K8HzdWnR45ckUrMeds',
  "Bloomin' Brands": 'Qma4z24FBjhrWtPGYWPFvWSekkyBgHZQQv9QrAFViqjuvY',
  'Bob Evans Restaurant': 'QmQGYSMzTbTsTggS8Jsk7ynckAHo98xgyDi4FLHwf6D3sN',
  "Bob's Discount Furniture": 'QmTC64ycqTwLfWmMS9o96csmNDqMF3yvtwQ7DT1FeFeJS4',
  'Bonanza Steakhouse': 'QmVc1uXjKEQxMgzTGHHrgwocR4WnPuEfuRk54BgZxMFdwq',
  'Bonefish Grill': 'QmQiTW6MVDXXa13Yyf9Trn5f4MrwYu6zLyRTPtWuR9bSwr',
  'Boot Barn': 'QmNzmtSWWhfYG72mcGBBK6d3ung7QEXyLLi8qK6ytCCvb1',
  "Boscov's": 'QmShHDvD5x39fzBaYGKtNJMKKhVzrem5gj7MWyXmKtDv5D',
  BOSE: 'QmNx7Y5FbZfgp67pTYbyGQ7isuJhyEc56DKwFRe3oeoxdL',
  'Bow Tie Cinemas': 'QmUdHTcscvqyHYBZLiBbjapU9m8jDEWDhseEME6QRpdsDn',
  Brighton: 'QmTMutamm4zzFbqy7sm781zBmFoCzfXfU2QQ3qX12weMrS',
  'Brinker Restaurants': 'QmR3Zi5Ctbic9jmHmzxnzd53aB7mv4Epvr5VVX3hSsCtsF',
  'Brooks Brothers': 'QmcLh1NN1B94nYibBvi3xibfohztrVBEqu6RCsjZUT7wsc',
  Brookstone: 'QmVruDbu1iksZjkHzChgi7fDqPNMPzzsFawwybRSRebdbV',
  'Brylane Home': 'QmPy4M4xfqbrjAvEhRgKpeoKmc75wR7ak3TVyrkiYWJA6p',
  'Buca di Beppo': 'QmTCLpfR4yw1kGS7crcBQJu2mdN9ZAhziaH3aR3ZynRvMU',
  'Buckhead Mountain Grill Restaurant':
    'QmVffY9nUZYPt8uBy1ra9aMvixc1NC6jT7JjFNUgsuqbpJ',
  'Build-A-Bear': 'QmUQ6WTAXaRaFzAQLhe1GtueiV5i9ZLW3aet4PUNpc11bb',
  Burberry: 'QmbKGvzRJVmniqWwHDcdPFcSgBJCcqA8p3oWGAkxeRo3jY',
  'Burger King': 'QmT7MZNEGf6ZB8qNvEihTsxUyjcEXzLkTRU7d9VndgPAP7',
  'Burke Williams Spa': 'QmdvVznKW2mvBzY3rW4q8oDRAW6uJ3uLNpL1FSrSr945d1',
  'Busken Bakery': 'QmWXCui8FQ4BdAAQJfLoCAf4VGbz2Z6zCLvfW7RJCKYyKG',
  "Cabela's": 'QmSTSwbDQrg9fXdAwj73JKrJJRHnzF57yzPdoguEYn7kcw',
  'California Pizza Kitchen': 'QmSJG7gZfYBmA58eJujGsQ4ZYPevBj2WmpZam8JoDn2Mg5',
  'Callaway Golf': 'QmeXF3BHnhT2q85s3YAkY4HD5ZVm7Kt7YcEUM5qZn8JF5r',
  'Calvin Klein': 'QmevRnbPj8sTF6m6zix8bGXHL4wTfQ36okZFwyYFMyE1pN',
  'Cameron Mitchell Restaurants':
    'QmVD8K1vJwywBBS5vGqKwpYWiwPQtHUijfxm919CeQrn6z',
  'Capital Grille': 'QmdSLrZje7mXycm6WuiaGss1Qsea9HSEaov6ADUbwxj87y',
  Carhartt: 'QmWHY7dyFwkto7PUjsm7xwF4fHed78mba1N4mbtV54jfWE',
  'Caribou Coffee': 'QmXJ63EpwxRhZB4sBpJzPcxpCkvLu2FzBsAnhSZydjrWqN',
  "Carrabba's Italian Grill": 'QmPRXkB8cKxBgEdxW5WkFtjUJqfTkA4MKcVkLZhio4e3kG',
  'Carson Pirie Scott': 'QmSy6TmWfXqhGBt5BcfCWsRmMdisFugaBPe1os8Zc5ya7D',
  "Carter's": 'QmNpCrMY9FXufz163BJ2fKBvicnjgUHjZoiDZkec8LhKtn',
  'Casual Male XL': 'QmVVVUWvdXpJPU5oXxsn4zSuQfsYkShR8W9KkHT2CZyv51',
  Catherines: 'QmWGdheLqMJ2wkBXWgjkNm1pY67Fxd256yvL3BiAcR4sre',
  Cato: 'QmVxJgfVD4CM9mQPfkgBhdd6XEzkGCqBGtVyfw1tNePZxT',
  "Cavender's": 'QmQzsaok6cD1v9f3ugFWKtXuxX1oZxSUN7S36f2VXN1RG1',
  CB2: 'QmauAA8HT7asCWuTe9SChwjzQNBy9GMZsJwKPJDHcbMHyh',
  'Celebrity Cruises': 'QmdntQGasSq28pfZAxcBReCV4NoBE6yzMhssE5RniwW3JE',
  'Champs Sports': 'QmPLnPPeFXNKtHPAYHSbZgxNBMbqmxkAch8m8Smcjbz5Mh',
  'Charming Charlie': 'Qmc1teyAaGsanjAMk2xTVhC1Z3FKhaUSiyaLXPe1yAACin',
  'Cheesecake Factory': 'QmbHf5zYYfYUuP1i8WKqKajaf5ky5NapKteK6x13YGjoTr',
  "Chico's": 'QmdzeeCvvLDj7Pr7umexTxqS7nP8DnbU3uMdgWuyq7M5uw',
  "Children's Place": 'QmYdwPo882udCv89ehpPwJ2mFgHTvgx8Jco9xcriNBFPKu',
  "Chili's": 'QmPcgZnCeVgUYvuDi9u5KEiaxexoi8rLLVxfh9X46fXEsn',
  Chipotle: 'QmPVFttN6oSi6WLfoceS2suQgKXfS4YrpiBVgtcaMcso3R',
  'Claim Jumper Restaurants': 'QmVLCzjRqEYFAyRtGouihvuepeXFu9DTByScqKhi3oSwuK',
  "Clark's Shoes": 'QmbpemwzzUwA6SSFkDgSTD9J1XRzSonsM89T4RAjdEkTEH',
  'Club Monaco': 'QmbCm42YEAn8akJL8TsjP76qVAfJxcdRFMAVik5msajMip',
  Coach: 'QmeiH8jkogedcWYa3Tpju3n4jTYdC6D4mPemJW5osBeMDt',
  'Cold Stone Creamery': 'QmbGCJWywoYjAYX2m5kkQyb6hofDv4c8pHAmz4BFn8WAX4',
  'Cole Haan': 'QmPixDfJpFhYssrbar91yGGvDUbVg7Lt2L3NayW1mpArxV',
  'Columbia Sportswear': 'QmPKabHmTu36KHiEsr3mchxpPpbMxQwhasdbCVvcqWXRUT',
  'CraftWorks Restaurants & Breweries':
    'QmXzSJtYvVbZEiApqPL8rqow4NaQqFkz4e6kwdu1Rc3DP1',
  'Crate & Barrel': 'QmWyamiukLK1Wza1hAU8iwkuibAYK6Tnc9VhViGNXhvhSv',
  "Damon's Grill": 'QmT4HRybxNih2FFpHLU7TDFwjNFmHKAsPXSTdKtxHGCQXs',
  'Darden Restaurants': 'QmULZSiBpov2BLrkQQoFMwb9Y4ZEESN2SuXutvYTeHV4ji',
  'DC Shoes': 'QmQErjJrofqEG5XJfvQBzhkDGrd7p2ZqLaR65ofC6m7HwZ',
  'Dean & DeLuca': 'QmVjti5A7eNK6B2ZZk4j3nexUhGk4uXSEeLrQdSsMtXWuz',
  "Delia's": 'QmReRUZvVHaAVrDRZnp9dgYuPufteyLk8yWiSVwjPMa4pa',
  Dell: 'QmYQEAgfa6jCtmFvusMGa7wjkXW9zT1k8pGdwfAX7Wb71A',
  'Design Within Reach': 'QmaMwpKCsSW6xpVsE2gwrVoM5hqYCP9g4yGFc1vMoJTs5u',
  'Destination Maternity': 'QmcW9UeHyY6KsZ1H3edtVPEGNMLoMzcctmqGZrw32QmzU5',
  'Destination XL': 'QmQps5uRC2nUxsjR9VjLCgRLyUr2wazD1ssQys7EvBV19u',
  "Dillard's": 'QmT4E2WHdhCvjavWDaeDkrbJ6FvAHHesUdzMenDXVKZ6P6',
  "Domino's Pizza": 'QmbgqLMhCKVcoU7sj1NJSgRh3n4jS3J3k2LN5wHigoJ1bH',
  'Don Pablos': 'QmXqLdo9Jnb1kesnB3JzLLh7oxsyrSoi2qMVk3yipsCRjj',
  DSW: 'Qmc6edaZrpG6kyTPo2nZ7mZWdhQu7EsWLDY7Yn9MVmh9Pn',
  'Eddie Bauer': 'QmPvuixwNeFvyyEKKR61KbuMfpPAAo85dXK85DUh1tNt4j',
  "Eddie V's Prime Seafood": 'QmRu2oPruPYfXu2VhjqCsA4CrANDiGqy5Fw5z33EAJJohy',
  "Einstein Bros & Noah's Bagels":
    'QmSETmkBZJwmCtNv5JND53GXHcHLZHZWHMiym4r2JxRue4',
  'Elephant Bar Restaurant': 'QmYjBtcFMPPLhzZRZiQqCVjP5FhMYaW7XGjmcBtmMMLncx',
  'Elie Tahari': 'QmWRBF3EZLHRB6n43hWxGMaq7TRqmAfNWUKCbSXnLDLBtH',
  Express: 'QmPr6XsDDHgPr2bZf2TjWEy6Pwyq2b9tFyxP2PR1pPLqiv',
  'Fairmont Hotels': 'QmSkDdqcFbZXMgtkkUy4h5EzJ2ev1JkiQUL6y7TmND5cWr',
  'Famous Footwear': 'QmeysKnd1rxWzubGYHRvq2mcCjjc5GDTRgbnMpAD7Zaix2',
  Fandango: 'Qmck6cM4YZH3hTaUxo9C4YrtTqCbYtqBHrF3KLANq6yxJb',
  'Field & Stream': 'QmZtP8bGh9YvTCr4kUAkhN2LB8dtGkRiCh9YJPSg2Bsvo4',
  Filson: 'QmUYaDi5w8mqknxKVZkwBc3uqzg6SK6uXZDcpusevEpkJW',
  'First Watch Cafe': 'QmPED91RGtfnyuMwy8P5rhExKG3ECckQJG9WF2H9iGVGU5',
  "Fleming's Steakhouse": 'QmQqkSjdTv8N8jUFtyATFRJr858gFbHVj1aQ25BLpYsYfL',
  'Foot Locker': 'QmVsp94mRdeMpzVm9w1ktms7J1PWDFD5rB5VrMuyDh47xw',
  'Forever 21': 'QmZY94wwYHenXDap2XeEq9YNQfHEWW68mERKfc5TYir9YB',
  "Francesca's": 'QmRetwcG8EeDQ9cs1fTdQ27MDAhR5fJibsjNHM2xKdc4dK',
  Fuddruckers: 'QmTxSA2LFYruhUTxi8FyJ3TeybRq4xFpqTyeDdvboLKYut',
  Gap: 'QmYSQnmeuvkFqCjkEhsMUxn3d8b9DGLHUcJK7wfTbpH6jY',
  'Gap Options': 'QmcKst14rNYJCpEDEsGzRUNLGFzP1DAZDJtoiouj8sDyFa',
  'Google Play': 'QmZ4Farc6jpVhxw8BGR53By2gvsifpuaNjEvJpHMUXbSfn',
  'Gordon Biersch': 'QmPVYypVUGdJpgYmP3o4nBDgCLi1iTucqoQwndtcvpr4jH',
  "Grinder's Above & Beyond": 'QmVkjMt474GywBAdnLiH2Q2epKCiYMJHSrhnBoGx4wgihS',
  'Grotto/La Griglia': 'QmX4wdBg4iDXtbKwnnvhf6bZrRWnPdmu6L1GXZB2MPCUGE',
  'Guitar Center': 'QmenezpcChpvoMQpg5f4H2vbxYiCJs8S3Cjh4gxgf9c5cV',
  'Harbor Freight': 'QmRijti12hYjMd9oJ9bb4FfR8Dcn5bYVbfBCVjYU1rYqQa',
  'Hard Rock Cafe': 'QmVQwVc9qeNdMLtADm6V8ywYDahGxVZYAYYTKnScimN6yb',
  'Harley Davidson': 'QmXC5nrwkKa7oArs6X346mEZ7w9nTjJc724r4aMdGrz5Wh',
  'Harry and David Gifts': 'QmeHDMmZySeESLFgSTGMKuXeuh7AtWPMLL97LtCw2izsCZ',
  Hautelook: 'QmVffY9nUZYPt8uBy1ra9aMvixc1NC6jT7JjFNUgsuqbpJ',
  'Hobby Lobby': 'QmVzS7BPBo2vT6T8gkwEQdDskauMbjRSDnsXHemguKR8Se',
  'Hobby Town': 'QmVzDfKFVcxBrytXai2eTXHWPYTTA1yzseT3NtA6cSGLSE',
  Hollister: 'QmYTS2P4fgmBmfs5j6goKLeCrwuhgDW7ubX9zSL6Rp1EWi',
  'Honey Baked Ham': 'QmcVSwim7UAKuZW8PF57i8M3mHM2nwZNEevPmcuVUABEbp',
  'Hotels.com': 'QmXWPx9iZ75wHrnW3CJh6GjEtkeJcYDtw4gCTMJaFwjaSB',
  IHOP: 'QmQd2kudSd5ENV59d7G9JAQcNAipcmjs2T3tekMCaDgkDd',
  'iPic Theaters': 'Qmew2Aqdken1mBX6Heu28LMv1jG1Kv6cWUhGC3KAXg4F2e',
  'Janie and Jack': 'QmcVSW5yMa5CPVZNAxQxBgQfp5eH2xHVjy3gQui88jmSir',
  JCPenney: 'QmfRaJXEWMoNxMiT5VJuGM49uoqwD8GJeZrxbzeLy357Zi',
  'Jiffy Lube': 'QmZMYjd1xBrbb5joX47AAYAyS99sZqSEke3NhH8s6etx5x',
  'Johnston and Murphy': 'Qma7VbjyUdCRkw6qd5gz2qP3rxf47sn5BbkEAGkxHpxtrF',
  'Jos. A. Bank': 'QmdmLAZbFCHP4zXfnajNjFW2GUUp5EaqBeaKSWG8kDcYKH',
  Justice: 'QmPKjmT5jG2Jo7usUsWXRd4tB4YECzmPYGYy6KjoqFcnFx',
  "Kiehl's": 'QmZMXPQSe3ixoVLcuEPERcmFvsmkXfNqkqrkbp7173YGX6',
  "Kincaid's Restaurants": 'QmcVwTmjTVjxySyVS63t7v8Vn6rhMjG6ssE6bTLMBzhSYj',
  'Kings Isle Pirate': 'QmTsc7gL4kiZkSctD1qSoof3wqxHkVPz7TyQEukNiSotcF',
  "Kirkland's": 'QmVAQxZqeNyDsQKPz8XUdF8gmnSf4cuDhKJY3KCEDzvQGU',
  "Kohl's": 'QmPxb6oTqwyjX1zRfx4H2rqLYcmBBm7CYw7RokUg743r98',
  'Kona Grill': 'QmbBKE6t8zPxMPYJKc3F6Lgzuk6upzhisdXRSo8e35uFJB',
  'L.L. Bean': 'QmcRKEqA1XKD7JBB8xtZqH695E2fNQLKBzJthtwdnqvguM',
  Lacoste: 'QmfQcADxB3wDR7gYUEgVEzcAfSkqqEGtSo8SYrf9jfQ3ig',
  'Lady Foot Locker': 'QmQx79DSDyLVpsPeDDQq2AvE1rkm7L9FLvmv1QYDX5z5rJ',
  'Land of Nod': 'QmTSF9hXYwvJtr16efGd6ewHwUViBTpsDM8kMufaU3ZBVe',
  "Land's End": 'Qmdia31Gjvv3SqnYRdsvapvAtLkW4VMK3LdHWuhta7niWN',
  "Landry's": 'QmRg4Vh7yUfa42QAaeX9QGi4wUmLrQFc3MydQBLoFsceYi',
  'Lane Bryant': 'QmTHKxCtXzLsiWhmE4iQvCCZFeCRJ8B7hg3jC3H4CKQ7Fi',
  'Legal Sea Foods': 'QmQeZQE8Zs3k5ByaAqBV7izNo3P31xSayqh5FgKb3fk4iZ',
  'Lettuce Entertain You': 'QmQZz49fqWA9pnMzDpr2WujHYAzazzipibB1m2Dbj6tK7y',
  "Levi's": 'QmZCtM1tRQ9ZLcaiMtq9rMz8Rmg2UnxWq9axCgWDTCAJc4',
  'Lids/Hat World': 'QmbnDCGBkmjicg6SGZzX1Epoo2YmDLEggaLcaFbYgqs5Zy',
  "Logan's Roadhouse": 'QmYDMMhVTonThPhFD1tpAG9fk4pESohK4RCvYAZPyZRkCv',
  'Lone Star Steakhouse': 'QmSNLvfY1fa4KeRdro7cNwTSY4mRm2jmdM5ekGMp5jeYnh',
  'LongHorn Steakhouse': 'QmZxwvf9dPDz92wPFvH8g1Tb3pTcsKBf6EuBzd7TT2D2Wp',
  'Lord & Taylor': 'QmNhmZ5FGMhykuZwJ9za2YQB79ZYLNNZfkCYiuYVmMeLJE',
  "Lucille's BBQ": 'QmXpyVKtrQXqSmJ98kwJgR4ik1fvcqC8bYzRPsghjEQ6R9',
  'Lucky Brand Jeans': 'QmdEnrxFbdbMaVBUQVDFaULbjT1D1o1bwRdjLxSxk1jSPx',
  'Lululemon Athletica': 'QmQ8XN62rzXbJRompUTfonMPAuUdmbubR7AsVSNWRFBG6i',
  'MAC Cosmetics': 'QmQQH3EJpP2pPpk247AWwzGB8TJN2a15gUTonT2nA96ULD',
  'Macaroni Grill': 'QmbK8QK5wpP3pjp9NN2ZRhd4UtVbFSNy7VDMFymUWsi4zu',
  "Macy's": 'QmQAoxwGJkeWzTs5R9t8i9EQq78Gt1c9Dr9bGtukwGnrxL',
  Madewell: 'QmcqzPWE4ZYjK6LoGZRubs2MtCN2Rrmw8JXn2nk7qpqd6R',
  "Maggiano's Little Italy": 'QmT1mguUkjJVWiPw8UbNJcx8Eh2ztXWkM64mnPYwBqPFfh',
  Mandee: 'QmPL828prjeCqgZN9pScoCxen9ePcvJL9KpQHnwzbrxEyP',
  'Marcus Theatres': 'QmdUZ1bht5V1Fs7nYqxiEz2izENgvUX7AkyUDyug3tVLdT',
  Marriott: 'QmSBALgx9eTbcbUucub2L47szh4dHC2EYrPhZ21MMKtxGG',
  "Max & Erma's Restaurant": 'QmUQctjT2gFxTswBZvCCBu46qvhAyTi6kwZk7Q1r7dBW3Y',
  "Men's Wearhouse": 'QmU9yjGtE8czYbJivaZpUJNkBhHQpFBet3fqg6YsStiqG3',
  "Menchie's Frozen Yogurt": 'QmWWSvcKEfHWKwTE4vYXbBi9eAaue1yMhHxtR5vmtdUTCo',
  Michaels: 'QmNYR6mtNgDeKFUiyr3kQxJYLgGgQEthEowvEH89LC5Pfz',
  'Microsoft Xbox': 'QmNwtL1CBPUPbeMueTNQT1P9XHfgK9KaDi2Kkn4oWDUvJW',
  "Miguel's Jr.": 'QmbZvR8RY5gjV1A2j3wigjYrb7uk1nARW9oJLK8PeCYWM7',
  'Mission Inn': 'QmPs14mipBp6XQepSsUMJHRNg36woqE7MtwigGrnW5nqTU',
  'MLB.com': 'QmPrD4erRDywxA3Dp2DzkiNEhjbBx9gGV5gfwTLmQ71SGk',
  "Modell's Sporting Goods": 'QmVxjZVH4j3TFnfo9CQJwqdbbk6aXoj7BcnabuAJJBvJEe',
  "Morton's the Steakhouse": 'Qmc17MxSaqBezmrm7vexVA1LoGqJF3NNw7NfNS6QKCqjYP',
  'Motherhood Maternity': 'QmTDKt7gn5ZW8sFLhA9txnGQBkfy9Wzh3x2CLyCo9hGjkQ',
  'Naturalizer Shoes': 'QmRjfvkNUCKFJfa2DibJCGhZNJD3Hv8c3Q8NPX17mucMfk',
  'NBA Store': 'QmRW8k9r1WZQbUJ1mtM5L3NuWx73AoowMaBAX6fxENKVyj',
  Netflix: 'QmR9yMrARkQqWXFR7gGAkSwZEZAKb2kN4RKNcuiidUnzFA',
  'New Balance': 'QmQU5P5JyeNRPambHBZhEcf1y151Uj9jjhC1ek77W4F4Xc',
  NFLShop: 'QmVffY9nUZYPt8uBy1ra9aMvixc1NC6jT7JjFNUgsuqbpJ',
  Nike: 'QmWH75eumdDtcNBEWFN9VDvdLoLp1jXqEUqq5eQkNLUXj5',
  'Nine West': 'QmTQYbccqH4U1uqRyfobM3gD88DFTov8NXYybgs5wmr1EC',
  "Noah's Bagels": 'QmZ96YSSxGiJ8wq71rkhJwxd4gbbgf4bCkd1rCATR5Zr5V',
  Nordstrom: 'QmbD4gXEvnXVpMSrGqzG6Exm48Rby9bAu1Kn12bWHqwP55',
  "O'Charley's": 'QmR8fSae7wNPUgKRLfowosHxvo8jpwYX7wUPAE2qgD9q7x',
  'Oceanaire Restaurants': 'Qmf2tjTJTce7iL9CZrJNz8V75mLoC91YWUyPJsYUHfERYD',
  'Old Chicago': 'QmUYyqnJKqDXrfC72yX9cEGFeHq5yrPLaQDscFi22gzZ1Y',
  'Old Country Buffet': 'QmXyZbQJ6FidxHiRFmBQ6HgkveCKAdqwRGY9vKz9LdewuR',
  'Old Navy': 'QmNUQnUiwDuRpGtqZK9BZBbVkzWDbaosVNb6g5r5nuLPJH',
  'Old Spaghetti Factory': 'QmTxqQTBHbPtJsVw1rsbEQmB2e1Hop2mNFJqhv1u7irBqE',
  "Olga's Kitchen": 'QmVqjwTUnp5X8SnL2GgBURUSH1fCTRoxddFALvLMXW4aND',
  'Olive Garden': 'QmXeGxX86grzds6ZhXecjpbJHoSeSsHUooH54Wi7nEcEyz',
  'Omaha Steaks': 'QmP7BsWorUUV3AGXxVMsKjJT2vsTDRWww9efvjfS8G6cLD',
  'On the Border': 'Qmb6Q9tU8tV69UfPj3draFf6o1nFY8W3PvBskUjEKLMYDx',
  'Orchard Supply Hardware': 'QmVffY9nUZYPt8uBy1ra9aMvixc1NC6jT7JjFNUgsuqbpJ',
  'Outback Steakhouse': 'QmQw1cySmBBp2dcPEEHfTxFTdwbR7edtuNsGbACDqRrVa5',
  "P.F. Chang's": 'QmSY8mxUQg8xigu8z5ZVkkXJpPNa4eo4DiKb7Yzh9Sh29u',
  'Pac Sun': 'QmRFcWmSLYrtrsZbn1YfMxWMbNYpCdeZBxd8KxLpXMWu5H',
  Pandora: 'QmQkaoZUEo2fHmJhRGHo4j4G1MhixZFHsJjsQ5uvJVTo11',
  'Panera Bread': 'QmNkBEU7M3NunAFtDewrQVmpbiAfEf2QEVmFFaWzRrSf6o',
  'Pappas Restaurants': 'QmNV5VGhTc8oxvPFvhPRPPLBph6gVtn2vN82ziX5AxG34z',
  Patagonia: 'QmRd4cFcCWDy7BVqPF6hYNdxCrztnFE348ZunqJy2CTX7u',
  'Peets Coffee and Tea': 'QmQ13e8CaBEY4rBdeWgyAuCT1K8UKDQFkSW516tB5VgvN9',
  'Pei Wei Asian Diner': 'QmVffY9nUZYPt8uBy1ra9aMvixc1NC6jT7JjFNUgsuqbpJ',
  'Performance Bicycle': 'QmfTZaiSmBWYEbv5AqhiS9AyrTcZJPtax1CB1xBTGcFJV3',
  'Pet Supermarket': 'QmNSXnnXU4QePhTZFsYxGwCkcD98m9n2dSZC615ruKm2Mk',
  Petco: 'QmQvnRpD5yeftsaQGdcCxY1pnGg3DVepRKioDaB1Yt1X12',
  'PGA Tour Superstore': 'QmQA4DvEsJbYp5gT9nkphJB6ULobS85Bg74KuGEt68TDod',
  'Piada Italian Street Food': 'QmQKtPR5BdrwcvUVXUvY1av5oBoMXjTqmy4gvszMhtSksW',
  'Picture People': 'QmQriXKzDpXcYiVLmctFCtuWwnX3SgUR6MXbv7vUuNCp1m',
  'Pier 1 Imports': 'QmaJSczRTAteuXEySUM2CFZK4DUogGYB1ZoWyd7NZgjrH7',
  'Piercing Pagoda': 'QmbUzuZATzbGnK56uUWxpg6pXHzb3MMRe1VoqN4m2Kwap9',
  Pinkberry: 'QmdcaGzmDj7hVA1CfcrhkSEB7gzgSMcwS3BzVHVJMH4wku',
  Pinstripes: 'QmP8PfqSxXufE7LNj7reLGNTY5ktdKKSQVn61cpRosgoJv',
  'Pizzeria Uno': 'QmSnVfgCNzN4zaeizWCUoyvaE6ULY3785J6zkTsm8PCnP8',
  'Playstation Network': 'QmXwsL8rJhVSjdeoZ1herat3MLGToszGsWu177xQH1d3wR',
  'PotBelly Sandwich Shop': 'QmYTiRk5GnVx1UehsHKRaQwucD29cqYPV6eEfuAFtnTVpt',
  'Pottery Barn': 'QmPMchf7PusHw6FJ9cBA3RfKe33zRYvYoxRppn1ftRuSga',
  'Pottery Barn Kids': 'QmNmG6tsq4kXSivyWHUbQxmwEXyMFXJ39ebj4iPHdekE9m',
  'Quaker Steak & Lube Restaurant':
    'QmaEF81bvqZtp3zCNF5BQwQxKUDsnFHGSfBdigpqeXtZmy',
  Quiznos: 'QmTqE1vcpPKGDUpjoZLLxPDrBj9ETQV2j5T9FeXh8d5trz',
  'Rainforest Cafe': 'QmR2L8kxT8PfczJFGpJZYfQYK15PsfgEzFfDcoL7f22yEK',
  'Ralph Lauren': 'QmZjbTCB2oXj84LxWFyZEe8jtcti6S3T3fD4Qr7Mokd45V',
  'Raymour and Flanigan': 'QmQ5kAW72p6jEr4qEHoQ4Q9R5w4nFQXU6uhMwee5To7Mk1',
  'Red Door Spa': 'QmRDi1rEGwJPbFNNGNrFdxcpzNjjqjmBkc41PB613SGQHG',
  'Regal Entertainment Group': 'QmS9XUUqaATUcyUYnREtRzeWGsYXjY6bxUH7vAVhKVX2rX',
  RegencyTheaters: 'QmPWx794QxgQdki74nJvy4A4naAR6A3j2KaiT77vT53trR',
  REI: 'QmNcGvao7NMMGgeHwRB6YL1ny1KsEBx5Nib1FD25Ji4QXV',
  'Restaurants Unlimited': 'QmWAX6K5zEZ3KLbBCHnSDda1DFLFadFCitLUXmCiYpdouf',
  'Restoration Hardware': 'QmasJGeAKF94vuPJdJmijiMDnGsWartqU321SJq2npo7R7',
  'Rock Bottom Restaurant Brewery':
    'QmY8hbgSf9yHLBtPJQJkRZRHd6HSvRG5EFvZYYJg7mHMAu',
  'Rooms To Go': 'QmWACPymfVGxawh24FSFqZd5pmSRYYiSgopjYHLS45Jrvb',
  "Roy's Hawaiian Fusion": 'QmdnHftF5feT7M3NjrTo4ZGANWNEDJ1DfLQH6D8EDE67fo',
  'Ruby Tuesday': 'Qmbk5AVMQyumCgnkzNDmUuY8idqjwWBcc337FSBJBMEeUZ',
  'Rue 21': 'QmXqoyELhd1oZq1PJayVSKDKbzZqrbXyyh6GQae6sqEQLS',
  RVCA: 'QmRf4SMczShSEaDFjB93DkiijLCt1FajYAdiF4h6ftqwkJ',
  Safeway: 'QmQPvV8nsCervLchHuR3kRV9F9mfMEoRXLo6Tsquc4kCKR',
  'Saks Fifth Avenue': 'QmPQkh2u51ggbjEMJ43XgwwXR1bCBUHEiDQsCrXGvhHVaV',
  'Sally Beauty Supply': 'QmbFsdyAdnUa65ms8FMEXB6P4k4LaqZ9hUeU15kT1LSqZp',
  'Saltgrass Steak House': 'QmckV6vHeoFo9ipzjjLnEdEoYN97wxCrvy5LYchfNUHkdr',
  "Sam's Club": 'Qme2o66WbcjBDBxkji9KsUWDeKni7nYtG4ndf1MMWFMXwT',
  'Scene 75 Entertainment Center':
    'QmTVXCDnbLFeLv1yqKSekww1e7YVgkBatqb78qiNT5mp4K',
  'Scrubs & Beyond': 'QmVuLe5HTETFRu3sFNmjLzfcAm1VkPsjDADioRe15bW86j',
  Sears: 'QmSLPZehAeLLYCBH6JGhvJZHmnftkre34sA2U3SrdQTJd8',
  'Seasons 52': 'QmWWrBLT1W5Bo6bPnjg4Ughju1Rbd5qVAQ4Aw4WNYhccNU',
  "See's Candies": 'QmbQLEZqxTSoepshuU6HCsM5dvo8nbBqfRWkCuUdcPcger',
  Sephora: 'QmaP8eBdqzLQEv4bU9vs1S1NKDVaU2mDeVyB2ZJkC7XoML',
  Skechers: 'QmRvnXAYWMsFCiDziVBiMxQXZxj1d6n24z26hMMafUt9gt',
  Smashburger: 'QmerR4RSgAbaEjvtyoARdafbcEFCfZYSCPCtY9XNUmfGZo',
  'Smokey Bones': 'QmY5c4G9mTG4zsNJFWtQJHdSbbkdhsCZ1SiH5dvjmp7gy4',
  Soma: 'QmddTAN5a31fnAFYXJgd7jaojeTH4BnWCFZ6rN9r11qk7i',
  'Southwest Airlines': 'QmXRFWgtyTJuNCVpMPYTRTCwfbLthdf6c9ukT9od5AU6Vc',
  'Spa & Wellness': 'QmbJtch1igqSocZkhxNGT7Y3VN43hdSGvzrMVC36g8aMTM',
  SpaFinder: 'QmVdX7JwjrkAkfj2W6ZKcMkSfXrvkq5vZR6iFE8fETnmRJ',
  'Spaghetti Warehouse': 'QmU9MtyBeHDTru73PWY8CRa4is4YQBYYL8JQAcYWevXa6F',
  'Spaghetti Works': 'QmdZs9VXukWzpoHe8mvkQ7c9Ux5Ln7Tc8hH9UP1R8oKGjg',
  Sperry: 'QmdAZPLkthzJ3mcLHnhzvcC9KMBebR4eEqG1JKYhXDcsAe',
  Splendid: 'QmNsMPaqZPXwHkvJr3DsPv1Bi5kzpScm3PhYuGJ9CynfCJ',
  Staples: 'Qmczwf135H84cHW9jD6zZb1S3AN7csC63V8tvTkbz74zBb',
  'Steve Madden Shoes': 'QmT1BApsAVSFGbfsvUjgm359WqQcSYj8CJJzM3qgidEtop',
  Stubhub: 'QmdgTnijRn7tJvctinygxBgRzgdtyLf9kZDVL8tecC4aUn',
  Subway: 'QmP3JA2JUsDvZzDm21BFBtDxh4Bu3hVTL2dAwsS7caAHGT',
  'Sun and Ski Sports': 'QmQf9teDY2yPjy8sS5gRYgPiVvwBhdHTNb57iYFcCQCsJd',
  'Sunglass Hut': 'QmaraAPdok15A7GhcNBjwhbTQUw6kbTVB8DoRRqdyaREHf',
  Supercuts: 'QmZf1gdG7pdxdQAJg61KwuWZgARWN9VPYqNuLTCHSabiJo',
  'Sur La Table': 'QmfYj4KQW34f6kCxB42UMLGdyK1BhPPBH8Zb7fuYJFZ1hV',
  'T.J. Maxx': 'QmRtHLwj2GZRBJkbdwufvSunQi3M4izM9wbsVJ2QQZLjVC',
  'Taco Bell': 'QmZ15FpBGLVmGJVDqQT1p2f3EdXWWJGgPHt8NjbfHeLGhy',
  'Taco Time': 'QmYtkBvCt9TzmX5oV7Szj1VCNgrUThsDJjzkpug58uKdZW',
  'Texas Corral': 'Qme7UrqPsoUJbRHf1u8j7WVYisnipd8QEfyJuisL32JzvU',
  'Texas de Brazil': 'Qmf6wgHE66bz2BoESPVC4DKQRndGPTbWUeuvbWPkRamBga',
  'Texas Roadhouse': 'QmUYPeHoyKjZ6qeJf4mbW1UTkNjeFQ5BTwahpVQEcnsQHm',
  "TGI Friday's": 'QmT4mfuG5WYu4tD8fXS7P4PzVM6RXLRaaacSfLLv6ZeUgY',
  'The Art of Shaving': 'Qma5ydQB5YTGscn8zV1sa1MWqnVTgeft2Zuvx7cSSF8tDD',
  'The Company Store': 'QmcZ4JVhNhnixry3Pa4GyY8yC8evBZTkqs7Y9rXjFMFwkk',
  'The North Face': 'Qmcm2AM5DtBEmyGbW1mhu7cHHVtaWd6QSzUqXesLU6C8ha',
  'The Walking Company': 'Qmf6SKw5kp6QZin7pyfyxRXqUcXASsFF9LzNSiuL1X8ceo',
  'Think Geek': 'QmX31k6VL6UYBLBKQ3ZA5FFfZQsWamR83bW19NaXCaS1fg',
  'Tiffany & Co.': 'QmQYdyLK7289MuqiUoicgFEuCUz16LKt8qVmrgJ6T32wXF',
  "Tilly's": 'QmVffY9nUZYPt8uBy1ra9aMvixc1NC6jT7JjFNUgsuqbpJ',
  'Tommy Bahama': 'QmbM6qwD4yKgPy9ti3mtkdcABaEsNyTGToHfq6MMRBfqSX',
  'Tommy Hilfiger (Online only)':
    'QmZqAUXY7LRk4yGXjsyNc2qveXhnccTTiSFb14ESfUfezk',
  Toms: 'QmRVZGUHqTphrqX914cGMBPyrNeCHCYGrLExsepyCsw9fZ',
  Topshop: 'QmVzsLv3cmzmBQw9KTHM7pEjn1HEj4pa891RaCvfBLerLG',
  Torrid: 'QmQ5mA4VNkS4JfYV448eMy8rBhpUt64jhPDk7XaGD89JrH',
  'True Religion Brand Jeans': 'QmVY7h4tqwxn6B16gqRgZT9cDhmsW8jPs9fKZEQvGWEdQu',
  "Tully's Coffee": 'QmPdYw6MTRG73wNd8pfaZx8K9kD4u1P4CC55B3LsJoDp1N',
  Tumi: 'QmPfHwuBisMV9yLUzx9b663e1hgyKecYVAgCSwfyyZotvr',
  Uber: 'QmYrMZojAwheCxe59v94VmK2XiSwAtFpXBTER4djoWfHie',
  ULTA: 'QmQrfnvqqFAq6Li76z3LwiNYyJPuf6i7mEzhnEmoQJKSd1',
  'Under Armour': 'Qmbi1QE66WVj9P5ad85fVa5MFc9DXmMKVwVoMnyZod1Y2E',
  'Uno Chicago Grill': 'QmbQQsdLNTBj4hBdTBHJoU5m8KjTJhfkRPPsyxyxRfdSF1',
  'Valentinos Restaurants': 'QmbUUiY7DjNVgcRM9ab3VcD4KANUuwuppsxT2bFLQqLvpY',
  Vanity: 'QmQZkJXidYJJXY8w2sjxqe1PxsmZ24sPi1jXEc4TqiniQH',
  'Vera Bradley': 'QmV7bUfHg4JpAw5poZPymw9zRy4kyYWkPGCwLjhZFdfJQD',
  "Victoria's Secret": 'QmT1RDMa3JNgxckrxga8CCSM94zctJEXpauDktruzncYKw',
  'Vineyard Vines': 'QmYaZYv4AAArKiKq6tRjpoTMvbEYEHdhuPmQjAeYD3qjxJ',
  'Watch Station International':
    'QmYMdxL7HUsGs4wZZQaWXZH3NkVggriuA6ichyfEjnyfFo',
  'West Elm': 'QmS2UZK9oMugyaLpiF4FRJWqsoqxmM3kcq26dqK4AP6x6Q',
  'White House Black Market': 'QmXBNm41DkQNUiCzUP6TTVFVt25L5A2BWjv7sgGpgYC279',
  'Williams-Sonoma': 'QmTVZw1wsnmQv3ii2qZjaoeoZtb7aszD4PEJN1xsPFXCBE',
  "Willie G's": 'QmZchxP9NUFfL3u35rwrfH1c7DMiNereUBf2gvYNeWGeqV',
  "Wilson's Leather": 'QmSBuoKEqhHqcFZBNPx8JFEtDcxA88V6VPsxrhd46zKmmE',
  'World of Beer': 'QmdSbfoAi562EnBxb17vPA6iZtCkjbo2Zphg47MGqZkZTo',
  'Worldwide Golf Shops': 'QmX1SPQC44GGqwMVQdk4ZVuKnp2EqCW526m75YRzMHFsCm',
  'Yard House': 'QmYgZRMcG79J68NZkUQNkQbQu15ydtsbGUD53WuYD3wemU',
  'Yogurt Mountain': 'QmWrr4zMevUvVJqvNCnRQQPVewY1xTKtWxs1o5psJBwdTy',
  Yogurtland: 'QmSkQLzmRfCw7veCPkoAPBoWGWMi6GixqCQTfyf4gDxztH',
  'Z Gallerie': 'Qmb2KZ1mEvGwPG6Caon6MJGkiFHiwCc5Yt54uaX1nNUh37',
  Zales: 'QmUMUd15h6GP8dAbUAdSK5CQrDnv2TyFYNKqxQ7MhG9h1b',
  Zara: 'QmVffY9nUZYPt8uBy1ra9aMvixc1NC6jT7JjFNUgsuqbpJ'
}
