module.exports = {
  // Event actions.
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  GRANT_TRANSFER_DONE: 'GRANT_TRANSFER_DONE',
  GRANT_TRANSFER_FAILED: 'GRANT_TRANSFER_FAILED',
  GRANT_TRANSFER_REQUEST: 'GRANT_TRANSFER_REQUEST'
}
