module.exports = {
  // Event actions.
  LOCKUP_REQUEST: 'LOCKUP_REQUEST',
  LOCKUP_DONE: 'LOCKUP_DONE',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  TRANSFER_DONE: 'TRANSFER_DONE',
  TRANSFER_FAILED: 'TRANSFER_FAILED',
  TRANSFER_REQUEST: 'TRANSFER_REQUEST'
}
