export default [
  { code: 'ad', name: 'Andorra', prefix: '376' },
  { code: 'ae', name: 'United Arab Emirates', prefix: '971' },
  { code: 'af', name: 'Afghanistan', prefix: '93' },
  { code: 'ag', name: 'Antigua and Barbuda', prefix: '1268' },
  { code: 'ai', name: 'Anguilla', prefix: '1264' },
  { code: 'al', name: 'Albania', prefix: '355' },
  { code: 'am', name: 'Armenia', prefix: '374' },
  { code: 'ao', name: 'Angola', prefix: '244' },
  { code: 'aq', name: 'Antarctica', prefix: '672' },
  { code: 'ar', name: 'Argentina', prefix: '54' },
  { code: 'at', name: 'Austria', prefix: '43' },
  { code: 'au', name: 'Australia', prefix: '61' },
  { code: 'aw', name: 'Aruba', prefix: '297' },
  { code: 'az', name: 'Azerbaijan', prefix: '994' },
  { code: 'ba', name: 'Bosnia and Herzegovina', prefix: '387' },
  { code: 'bb', name: 'Barbados', prefix: '1246' },
  { code: 'bd', name: 'Bangladesh', prefix: '880' },
  { code: 'be', name: 'Belgium', prefix: '32' },
  { code: 'bf', name: 'Burkina Faso', prefix: '226' },
  { code: 'bg', name: 'Bulgaria', prefix: '359' },
  { code: 'bh', name: 'Bahrain', prefix: '973' },
  { code: 'bi', name: 'Burundi', prefix: '257' },
  { code: 'bj', name: 'Benin', prefix: '229' },
  { code: 'bm', name: 'Bermuda', prefix: '1441' },
  { code: 'bn', name: 'Brunei Darussalam', prefix: '673' },
  { code: 'bo', name: 'Bolivia, Plurinational State of', prefix: '591' },
  { code: 'br', name: 'Brazil', prefix: '55' },
  { code: 'bs', name: 'Bahamas', prefix: '1242' },
  { code: 'bt', name: 'Bhutan', prefix: '975' },
  { code: 'bw', name: 'Botswana', prefix: '267' },
  { code: 'by', name: 'Belarus', prefix: '375' },
  { code: 'bz', name: 'Belize', prefix: '501' },
  { code: 'ca', name: 'Canada', prefix: '1' },
  { code: 'cd', name: 'Congo', prefix: '243' },
  { code: 'cf', name: 'Central African Republic', prefix: '236' },
  { code: 'cg', name: 'Congo', prefix: '242' },
  { code: 'ch', name: 'Switzerland', prefix: '41' },
  { code: 'ci', name: "Côte d'Ivoire", prefix: '225' },
  { code: 'ck', name: 'Cook Islands', prefix: '682' },
  { code: 'cl', name: 'Chile', prefix: '56' },
  { code: 'cm', name: 'Cameroon', prefix: '237' },
  { code: 'cn', name: 'China', prefix: '86' },
  { code: 'co', name: 'Colombia', prefix: '57' },
  { code: 'cr', name: 'Costa Rica', prefix: '506' },
  { code: 'cu', name: 'Cuba', prefix: '53' },
  { code: 'cv', name: 'Cabo Verde', prefix: '238' },
  { code: 'cw', name: 'Curaçao', prefix: '599' },
  { code: 'cy', name: 'Cyprus', prefix: '357' },
  { code: 'cz', name: 'Czechia', prefix: '420' },
  { code: 'de', name: 'Germany', prefix: '49' },
  { code: 'dj', name: 'Djibouti', prefix: '253' },
  { code: 'dk', name: 'Denmark', prefix: '45' },
  { code: 'dm', name: 'Dominica', prefix: '1767' },
  { code: 'do', name: 'Dominican Republic', prefix: '1849' },
  { code: 'dz', name: 'Algeria', prefix: '213' },
  { code: 'ec', name: 'Ecuador', prefix: '593' },
  { code: 'ee', name: 'Estonia', prefix: '372' },
  { code: 'eg', name: 'Egypt', prefix: '20' },
  { code: 'er', name: 'Eritrea', prefix: '291' },
  { code: 'es', name: 'Spain', prefix: '34' },
  { code: 'et', name: 'Ethiopia', prefix: '251' },
  { code: 'fi', name: 'Finland', prefix: '358' },
  { code: 'fj', name: 'Fiji', prefix: '679' },
  { code: 'fk', name: 'Falkland Islands (Malvinas)', prefix: '500' },
  { code: 'fm', name: 'Micronesia, Federated States of', prefix: '691' },
  { code: 'fo', name: 'Faroe Islands', prefix: '298' },
  { code: 'fr', name: 'France', prefix: '33' },
  { code: 'ga', name: 'Gabon', prefix: '241' },
  { code: 'gb', name: 'United Kingdom', prefix: '44' },
  { code: 'gd', name: 'Grenada', prefix: '1473' },
  { code: 'ge', name: 'Georgia', prefix: '995' },
  { code: 'gf', name: 'French Guiana', prefix: '594' },
  { code: 'gh', name: 'Ghana', prefix: '233' },
  { code: 'gi', name: 'Gibraltar', prefix: '350' },
  { code: 'gl', name: 'Greenland', prefix: '299' },
  { code: 'gm', name: 'Gambia', prefix: '220' },
  { code: 'gn', name: 'Guinea', prefix: '224' },
  { code: 'gp', name: 'Guadeloupe', prefix: '590' },
  { code: 'gq', name: 'Equatorial Guinea', prefix: '240' },
  { code: 'gr', name: 'Greece', prefix: '30' },
  { code: 'gt', name: 'Guatemala', prefix: '502' },
  { code: 'gw', name: 'Guinea-Bissau', prefix: '245' },
  { code: 'gy', name: 'Guyana', prefix: '592' },
  { code: 'hk', name: 'Hong Kong', prefix: '852' },
  { code: 'hn', name: 'Honduras', prefix: '504' },
  { code: 'hr', name: 'Croatia', prefix: '385' },
  { code: 'ht', name: 'Haiti', prefix: '509' },
  { code: 'hu', name: 'Hungary', prefix: '36' },
  { code: 'id', name: 'Indonesia', prefix: '62' },
  { code: 'ie', name: 'Ireland', prefix: '353' },
  { code: 'il', name: 'Israel', prefix: '972' },
  { code: 'in', name: 'India', prefix: '91' },
  { code: 'iq', name: 'Iraq', prefix: '964' },
  { code: 'ir', name: 'Iran, Islamic Republic of', prefix: '98' },
  { code: 'is', name: 'Iceland', prefix: '354' },
  { code: 'it', name: 'Italy', prefix: '39' },
  { code: 'jm', name: 'Jamaica', prefix: '1876' },
  { code: 'jo', name: 'Jordan', prefix: '962' },
  { code: 'jp', name: 'Japan', prefix: '81' },
  { code: 'ke', name: 'Kenya', prefix: '254' },
  { code: 'kg', name: 'Kyrgyzstan', prefix: '996' },
  { code: 'kh', name: 'Cambodia', prefix: '855' },
  { code: 'ki', name: 'Kiribati', prefix: '686' },
  { code: 'km', name: 'Comoros', prefix: '269' },
  { code: 'kn', name: 'Saint Kitts and Nevis', prefix: '1869' },
  { code: 'kp', name: 'North Korea', prefix: '850' },
  { code: 'kr', name: 'South Korea', prefix: '82' },
  { code: 'kw', name: 'Kuwait', prefix: '965' },
  { code: 'ky', name: 'Cayman Islands', prefix: '1345' },
  { code: 'la', name: "Lao People's Democratic Republic", prefix: '856' },
  { code: 'lb', name: 'Lebanon', prefix: '961' },
  { code: 'lc', name: 'Saint Lucia', prefix: '1758' },
  { code: 'li', name: 'Liechtenstein', prefix: '423' },
  { code: 'lk', name: 'Sri Lanka', prefix: '94' },
  { code: 'lr', name: 'Liberia', prefix: '231' },
  { code: 'ls', name: 'Lesotho', prefix: '266' },
  { code: 'lt', name: 'Lithuania', prefix: '370' },
  { code: 'lu', name: 'Luxembourg', prefix: '352' },
  { code: 'lv', name: 'Latvia', prefix: '371' },
  { code: 'ly', name: 'Libya', prefix: '218' },
  { code: 'ma', name: 'Morocco', prefix: '212' },
  { code: 'mc', name: 'Monaco', prefix: '377' },
  { code: 'md', name: 'Moldova, Republic of', prefix: '373' },
  { code: 'me', name: 'Montenegro', prefix: '382' },
  { code: 'mg', name: 'Madagascar', prefix: '261' },
  { code: 'mh', name: 'Marshall Islands', prefix: '692' },
  { code: 'mk', name: 'Macedonia, Republic of', prefix: '389' },
  { code: 'ml', name: 'Mali', prefix: '223' },
  { code: 'mm', name: 'Myanmar', prefix: '95' },
  { code: 'mn', name: 'Mongolia', prefix: '976' },
  { code: 'mo', name: 'Macao', prefix: '853' },
  { code: 'mp', name: 'Northern Mariana Islands', prefix: '1670' },
  { code: 'mq', name: 'Martinique', prefix: '596' },
  { code: 'mr', name: 'Mauritania', prefix: '222' },
  { code: 'ms', name: 'Montserrat', prefix: '1664' },
  { code: 'mt', name: 'Malta', prefix: '356' },
  { code: 'mu', name: 'Mauritius', prefix: '230' },
  { code: 'mv', name: 'Maldives', prefix: '960' },
  { code: 'mw', name: 'Malawi', prefix: '265' },
  { code: 'mx', name: 'Mexico', prefix: '52' },
  { code: 'my', name: 'Malaysia', prefix: '60' },
  { code: 'mz', name: 'Mozambique', prefix: '258' },
  { code: 'na', name: 'Namibia', prefix: '264' },
  { code: 'nc', name: 'New Caledonia', prefix: '687' },
  { code: 'ne', name: 'Niger', prefix: '227' },
  { code: 'ng', name: 'Nigeria', prefix: '234' },
  { code: 'ni', name: 'Nicaragua', prefix: '505' },
  { code: 'nl', name: 'Netherlands', prefix: '31' },
  { code: 'no', name: 'Norway', prefix: '47' },
  { code: 'np', name: 'Nepal', prefix: '977' },
  { code: 'nr', name: 'Nauru', prefix: '674' },
  { code: 'nu', name: 'Niue', prefix: '683' },
  { code: 'nz', name: 'New Zealand', prefix: '64' },
  { code: 'om', name: 'Oman', prefix: '968' },
  { code: 'pa', name: 'Panama', prefix: '507' },
  { code: 'pe', name: 'Peru', prefix: '51' },
  { code: 'pf', name: 'French Polynesia', prefix: '689' },
  { code: 'pg', name: 'Papua New Guinea', prefix: '675' },
  { code: 'ph', name: 'Philippines', prefix: '63' },
  { code: 'pk', name: 'Pakistan', prefix: '92' },
  { code: 'pl', name: 'Poland', prefix: '48' },
  { code: 'pm', name: 'Saint Pierre and Miquelon', prefix: '508' },
  { code: 'pr', name: 'Puerto Rico', prefix: '1939' },
  { code: 'pt', name: 'Portugal', prefix: '351' },
  { code: 'pw', name: 'Palau', prefix: '680' },
  { code: 'py', name: 'Paraguay', prefix: '595' },
  { code: 'qa', name: 'Qatar', prefix: '974' },
  { code: 're', name: 'Réunion', prefix: '262' },
  { code: 'ro', name: 'Romania', prefix: '40' },
  { code: 'rs', name: 'Serbia', prefix: '381' },
  { code: 'ru', name: 'Russian Federation', prefix: '7' },
  { code: 'rw', name: 'Rwanda', prefix: '250' },
  { code: 'sa', name: 'Saudi Arabia', prefix: '966' },
  { code: 'sb', name: 'Solomon Islands', prefix: '677' },
  { code: 'sc', name: 'Seychelles', prefix: '248' },
  { code: 'sd', name: 'Sudan', prefix: '249' },
  { code: 'se', name: 'Sweden', prefix: '46' },
  { code: 'sg', name: 'Singapore', prefix: '65' },
  {
    code: 'sh',
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    prefix: '290'
  },
  { code: 'si', name: 'Slovenia', prefix: '386' },
  { code: 'sk', name: 'Slovakia', prefix: '421' },
  { code: 'sl', name: 'Sierra Leone', prefix: '232' },
  { code: 'sm', name: 'San Marino', prefix: '378' },
  { code: 'sn', name: 'Senegal', prefix: '221' },
  { code: 'so', name: 'Somalia', prefix: '252' },
  { code: 'sr', name: 'Suriname', prefix: '597' },
  { code: 'ss', name: 'South Sudan', prefix: '211' },
  { code: 'st', name: 'Sao Tome and Principe', prefix: '239' },
  { code: 'sv', name: 'El Salvador', prefix: '503' },
  { code: 'sx', name: 'Sint Maarten (Dutch part)', prefix: '1721' },
  { code: 'sy', name: 'Syrian Arab Republic', prefix: '963' },
  { code: 'sz', name: 'Swaziland', prefix: '268' },
  { code: 'tc', name: 'Turks and Caicos Islands', prefix: '1649' },
  { code: 'td', name: 'Chad', prefix: '235' },
  { code: 'tg', name: 'Togo', prefix: '228' },
  { code: 'th', name: 'Thailand', prefix: '66' },
  { code: 'tj', name: 'Tajikistan', prefix: '992' },
  { code: 'tk', name: 'Tokelau', prefix: '690' },
  { code: 'tl', name: 'Timor-Leste', prefix: '670' },
  { code: 'tm', name: 'Turkmenistan', prefix: '993' },
  { code: 'tn', name: 'Tunisia', prefix: '216' },
  { code: 'to', name: 'Tonga', prefix: '676' },
  { code: 'tr', name: 'Turkey', prefix: '90' },
  { code: 'tt', name: 'Trinidad and Tobago', prefix: '1868' },
  { code: 'tv', name: 'Tuvalu', prefix: '688' },
  { code: 'tw', name: 'Taiwan, Province of China', prefix: '886' },
  { code: 'tz', name: 'Tanzania, United Republic of', prefix: '255' },
  { code: 'ua', name: 'Ukraine', prefix: '380' },
  { code: 'ug', name: 'Uganda', prefix: '256' },
  { code: 'us', name: 'United States', prefix: '1' },
  { code: 'uy', name: 'Uruguay', prefix: '598' },
  { code: 'uz', name: 'Uzbekistan', prefix: '998' },
  { code: 'va', name: 'Holy See (Vatican City State)', prefix: '379' },
  { code: 'vc', name: 'Saint Vincent and the Grenadines', prefix: '1784' },
  { code: 've', name: 'Venezuela, Bolivarian Republic of', prefix: '58' },
  { code: 'vg', name: 'Virgin Islands, British', prefix: '1284' },
  { code: 'vi', name: 'Virgin Islands, U.S.', prefix: '1340' },
  { code: 'vn', name: 'Viet Nam', prefix: '84' },
  { code: 'vu', name: 'Vanuatu', prefix: '678' },
  { code: 'wf', name: 'Wallis and Futuna', prefix: '681' },
  { code: 'ws', name: 'Samoa', prefix: '685' },
  { code: 'ye', name: 'Yemen', prefix: '967' },
  { code: 'za', name: 'South Africa', prefix: '27' },
  { code: 'zm', name: 'Zambia', prefix: '260' },
  { code: 'zw', name: 'Zimbabwe', prefix: '263' }
]
