"""change price column from int to numeric

Revision ID: 095a740dd6bc
Revises: 1a1da0e947fd
Create Date: 2018-05-25 16:00:01.528406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095a740dd6bc'
down_revision = '1a1da0e947fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listing', 'price',
                    existing_type=sa.INTEGER(),
                    type_=sa.Numeric(precision=10, scale=2),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listing', 'price',
                    existing_type=sa.Numeric(precision=10, scale=2),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    # ### end Alembic commands ###
