"""empty message

Revision ID: 0f3d8b023344
Revises: e6aa670ebebd
Create Date: 2018-04-25 12:26:45.571975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f3d8b023344'
down_revision = 'e6aa670ebebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_code', 'eth_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'verification_code',
        sa.Column(
            'eth_address',
            sa.NUMERIC(
                precision=50,
                scale=0),
            autoincrement=False,
            nullable=False))
    # ### end Alembic commands ###
