<<<<<<< HEAD
"""Add the Notification Endpoint table
=======
"""empty message
>>>>>>> adds review model and migrations

Revision ID: 12dac0fc84c8
Revises: 7eca0eca2ada
Create Date: 2018-05-14 20:36:23.854229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12dac0fc84c8'
down_revision = '7eca0eca2ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eth_notification_endpoint',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('eth_address', sa.String(length=255), nullable=True),
                    sa.Column('device_token', sa.String(length=255), nullable=True),
                    sa.Column('type', sa.Enum('APN', 'FCM', name='ethnotificationtypes'),
                              nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('verified', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(
        op.f('ix_eth_notification_endpoint_device_token'),
        'eth_notification_endpoint',
        ['device_token'],
        unique=False)
    op.create_index(
        op.f('ix_eth_notification_endpoint_eth_address'),
        'eth_notification_endpoint',
        ['eth_address'],
        unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_eth_notification_endpoint_eth_address'),
        table_name='eth_notification_endpoint')
    op.drop_index(
        op.f('ix_eth_notification_endpoint_device_token'),
        table_name='eth_notification_endpoint')
    op.drop_table('eth_notification_endpoint')
    # ### end Alembic commands ###
