"""add (transaction,log) to  event_tracker

Revision ID: 1a1da0e947fd
Revises: 3c046fce5916
Create Date: 2018-05-23 02:36:12.011692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1da0e947fd'
down_revision = '3c046fce5916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'event_tracker',
        'last_read',
        new_column_name='block_index')
    op.add_column(
        'event_tracker',
        sa.Column(
            'log_index',
            sa.Integer(),
            nullable=True))
    op.add_column(
        'event_tracker',
        sa.Column(
            'transaction_index',
            sa.Integer(),
            nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_tracker', 'transaction_index')
    op.drop_column('event_tracker', 'log_index')
    op.alter_column(
        'event_tracker',
        'block_index',
        new_column_name='last_read')
    # ### end Alembic commands ###
