"""adds role field

Revision ID: 3aaaae13285e
Revises: 12dac0fc84c8
Create Date: 2018-05-16 03:26:50.748533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '3aaaae13285e'
down_revision = '12dac0fc84c8'
branch_labels = None
depends_on = None


def upgrade():
    roles = postgresql.ENUM('buyer', 'seller', name='roles')
    roles.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review',
                  sa.Column('role', sa.Enum('buyer', 'seller', name='roles'),
                            nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'role')
    # ### end Alembic commands ###
    roles = postgresql.ENUM('buyer', 'seller', name='roles')
    roles.create(op.get_bind())
