"""add listing table

Revision ID: 47df3d43171e
Revises: 7ce715e56574
Create Date: 2018-04-15 09:18:55.718097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47df3d43171e'
down_revision = '7ce715e56574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing',
                    sa.Column('contract_address', sa.String(length=255), nullable=False),
                    sa.Column('owner_address', sa.String(length=255), nullable=True),
                    sa.Column('registry_id', sa.Integer(), nullable=True),
                    sa.Column('price', sa.Integer(), nullable=True),
                    sa.Column('units', sa.Integer(), nullable=True),
                    sa.Column('expired', sa.Boolean(), nullable=True),
                    sa.Column('ipfs_hash', sa.String(length=255), nullable=True),
                    sa.Column('ipfs_data', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('contract_address')
                    )
    op.create_index(
        op.f('ix_listing_owner_address'),
        'listing',
        ['owner_address'],
        unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_owner_address'), table_name='listing')
    op.drop_table('listing')
    # ### end Alembic commands ###
