"""empty message

Revision ID: 7ce715e56574
Revises: 
Create Date: 2018-04-02 19:55:29.747605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce715e56574'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity',
    sa.Column('eth_address', sa.Numeric(precision=50, scale=0), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('eth_address')
    )
    op.create_index(op.f('ix_identity_phone'), 'identity', ['phone'], unique=False)
    op.create_table('verification_code',
    sa.Column('eth_address', sa.Numeric(precision=50, scale=0), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('eth_address')
    )
    op.create_index(op.f('ix_verification_code_phone'), 'verification_code', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_code_phone'), table_name='verification_code')
    op.drop_table('verification_code')
    op.drop_index(op.f('ix_identity_phone'), table_name='identity')
    op.drop_table('identity')
    # ### end Alembic commands ###
