"""add purchase table

Revision ID: 7eca0eca2ada
Revises: 0f3d8b023344
Create Date: 2018-05-07 11:58:51.613814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eca0eca2ada'
down_revision = '0f3d8b023344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase',
    sa.Column('contract_address', sa.String(length=255), nullable=False),
    sa.Column('buyer_address', sa.String(length=255), nullable=True),
    sa.Column('listing_address', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('buyer_timeout', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['listing_address'], ['listing.contract_address'], ),
    sa.PrimaryKeyConstraint('contract_address')
    )
    op.create_index(op.f('ix_purchase_buyer_address'), 'purchase', ['buyer_address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_buyer_address'), table_name='purchase')
    op.drop_table('purchase')
    # ### end Alembic commands ###
