"""empty message

Revision ID: aabbc92d4366
Revises: 095a740dd6bc
Create Date: 2018-07-16 21:49:54.044235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aabbc92d4366'
down_revision = '095a740dd6bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verification_code_phone', table_name='verification_code')
    op.drop_column('verification_code', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_code', sa.Column('phone', sa.VARCHAR(length=20),
                  autoincrement=False, nullable=True))
    op.create_index('ix_verification_code_phone', 'verification_code', ['phone'],
                    unique=False)
    # ### end Alembic commands ###
