"""empty message

Revision ID: d2fd6720f94a
Revises: aabbc92d4366
Create Date: 2018-07-24 09:56:30.030103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2fd6720f94a'
down_revision = 'aabbc92d4366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verification_code_email', table_name='verification_code')
    op.drop_table('verification_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'verification_code',
        sa.Column(
            'code',
            sa.VARCHAR(
                length=10),
            autoincrement=False,
            nullable=True),
        sa.Column(
            'expires_at',
            postgresql.TIMESTAMP(
                timezone=True),
            autoincrement=False,
            nullable=True),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(
                timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=True),
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(
                timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=True),
        sa.Column(
            'email',
            sa.VARCHAR(
                length=256),
            autoincrement=False,
            nullable=True))
    op.create_index(
        'ix_verification_code_email',
        'verification_code',
        ['email'],
        unique=False)
    # ### end Alembic commands ###
