"""adds review table

Revision ID: db4655d7d379
Revises: 12dac0fc84c8
Create Date: 2018-05-21 15:38:51.294655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4655d7d379'
down_revision = '12dac0fc84c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('contract_address', sa.String(length=255), nullable=False),
                    sa.Column('reviewer_address', sa.String(length=255), nullable=True),
                    sa.Column('reviewee_address', sa.String(length=255), nullable=True),
                    sa.Column('rating', sa.Integer(), nullable=True),
                    sa.Column('ipfs_hash', sa.String(length=255), nullable=True),
                    sa.Column('ipfs_data', sa.JSON(), nullable=True),
                    sa.ForeignKeyConstraint(['contract_address'], ['purchase.contract_address'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(
        op.f('ix_review_reviewee_address'),
        'review',
        ['reviewee_address'],
        unique=False)
    op.create_index(
        op.f('ix_review_reviewer_address'),
        'review',
        ['reviewer_address'],
        unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_reviewer_address'), table_name='review')
    op.drop_index(op.f('ix_review_reviewee_address'), table_name='review')
    op.drop_table('review')
    # ### end Alembic commands ###
