"""empty message

Revision ID: e6aa670ebebd
Revises: eced346a4aad
Create Date: 2018-04-25 12:21:54.200391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6aa670ebebd'
down_revision = 'eced346a4aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_identity_phone', table_name='identity')
    op.drop_table('identity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'identity',
        sa.Column(
            'eth_address',
            sa.NUMERIC(
                precision=50,
                scale=0),
            autoincrement=False,
            nullable=False),
        sa.Column(
            'phone',
            sa.VARCHAR(
                length=20),
            autoincrement=False,
            nullable=True),
        sa.Column(
            'verified',
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(
                timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=True),
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(
                timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=True),
        sa.PrimaryKeyConstraint(
            'eth_address',
            name='identity_pkey'))
    op.create_index('ix_identity_phone', 'identity', ['phone'], unique=False)
    # ### end Alembic commands ###
