"""empty message

Revision ID: eced346a4aad
Revises: c73570688096
Create Date: 2018-04-24 13:45:09.327169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eced346a4aad'
down_revision = 'c73570688096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'verification_code',
        sa.Column(
            'email',
            sa.String(
                length=256),
            nullable=True))
    op.create_index(
        op.f('ix_verification_code_email'),
        'verification_code',
        ['email'],
        unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_verification_code_email'),
        table_name='verification_code')
    op.drop_column('verification_code', 'email')
    # ### end Alembic commands ###
