import moment from 'moment'

export default {
  listings: [
    {
      _id: '1foo2',
      active: true,
      category: 'Antiques',
      title: 'Title Here and Can Be Long like this',
      createdAt: moment('2018-03-13').toDate(),
      soldAt: moment('2018-03-14').toDate(),
      fulfilledAt: moment('2018-03-15').toDate(),
      receivedAt: moment('2018-03-16').toDate(),
    },
    {
      _id: '3bar4',
      active: false,
      category: 'Cars & Trucks',
      title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      status: 0,
      createdAt: moment('2018-03-13').toDate(),
      soldAt: null,
      fulfilledAt: null,
      receivedAt: null,
    },
    {
      _id: '5baz6',
      active: true,
      category: 'Tickets',
      title: 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua',
      status: 3,
      createdAt: moment('2018-03-13').toDate(),
      soldAt: moment('2018-03-14').toDate(),
      fulfilledAt: null,
      receivedAt: null,
    },
  ],
  notifications: [
    {
      _id: '1foo2',
      transactionType: 'purchased',
      address: '0x12Be343B94f860124dC4fEe278FDCBD38C102D88',
      name: 'Matt L',
      product: 'Super Lambo',
      readAt: null,
      role: 'sell',
    },
    {
      _id: '3bar4',
      transactionType: 'confirmed-receipt',
      address: '0x34Be343B94f860124dC4fEe278FDCBD38C102D88',
      name: 'Josh F',
      product: 'Wholesale Chicken',
      readAt: new Date(),
      role: 'sell',
    },
    {
      _id: '5baz6',
      transactionType: 'completed',
      address: '0x56Be343B94f860124dC4fEe278FDCBD38C102D88',
      name: 'Micah A',
      product: 'Blue Suede Shoes',
      readAt: null,
      role: 'buy',
    },
    {
      _id: '7qux8',
      transactionType: 'confirmed-withdrawal',
      address: '0x78Be343B94f860124dC4fEe278FDCBD38C102D88',
      readAt: new Date(),
      role: 'buy',
    },
  ],
}
