import React from 'react'

import { formInput, formFeedback } from '@/utils/formHelpers'
import ModalStep from '@/components/ModalStep'
import GoogleAuthenticatorIcon from '@/assets/google-authenticator.svg'

const TwoFactorStep = ({
  formState,
  onChangeFormState,
  onSubmit,
  onBackClick,
  isLoading,
  modalSteps,
  modalStepsCompleted
}) => {
  const input = formInput(
    formState,
    newState => onChangeFormState(newState),
    'text-center w-auto'
  )
  const Feedback = formFeedback(formState)

  return (
    <>
      <GoogleAuthenticatorIcon
        className="my-5"
        width="74"
        height="74"
        style={{ marginRight: '-36px' }}
      />
      <h1 className="mb-2">Enter your verification code</h1>
      <p className="text-muted">
        Enter the code generated by your authenticator app
      </p>
      <form onSubmit={onSubmit}>
        <div className="form-group mb-5">
          <label htmlFor="code">Verification code</label>
          <input {...input('code')} placeholder="Enter code" type="number" />
          {Feedback('code')}
        </div>
        <div className="actions">
          <div className="row">
            <div className="col d-none d-md-block">
              <button
                type="button"
                className="btn btn-outline-primary btn-lg"
                onClick={onBackClick}
              >
                Back
              </button>
            </div>
            <div className="col text-center d-none d-md-block">
              <ModalStep
                steps={modalSteps}
                completedSteps={modalStepsCompleted}
              />
            </div>
            <div className="col text-sm-right mb-3 mb-sm-0">
              <button
                type="submit"
                className="btn btn-primary btn-lg"
                disabled={isLoading}
              >
                {isLoading ? 'Loading...' : 'Verify'}
              </button>
            </div>
          </div>
        </div>
      </form>
    </>
  )
}

export default TwoFactorStep
